# Generated by Django 4.2.24 on 2025-09-13 19:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_note_updated_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Note",
        ),
    ]
